### ISSUE TITLE
Inconsistency in module structure/naming

### ISSUE THREAD

**Issue by amarnamarpan** [ThuYShao/BERT-PLI-IJCAI2020#1]
There are import commands to non existent module names.
For example:
```python
# line no. 4 in formatter/__init__.py
from .nlp.BasicBertFormatter import BasicBertFormatter
# line no. 1 in model\__init__.py"
from .nlp.BasicBert import BasicBert
```
**Please note that these lines are trying to import modules that does not exist in the specified folders.**

**Comment by ThuYShao** [comment]
These are irrelevant modules. I have updated the corresponding codes. Thanks.
